# Generated by Django 2.2.4 on 2019-10-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostContent',
            new_name='Post',
        ),
    ]
