# Generated by Django 2.2.4 on 2019-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191003_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Qudus', max_length=50),
            preserve_default=False,
        ),
    ]
