# Generated by Django 2.2.4 on 2019-10-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191008_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_order_by_date',
        ),
    ]
