# Generated by Django 2.2.4 on 2019-10-08 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191008_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 8, 23, 25, 5, 5148, tzinfo=utc)),
        ),
    ]
