# Generated by Django 2.2.4 on 2019-10-09 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191009_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 9, 0, 7, 46, 584882, tzinfo=utc)),
        ),
    ]
