# Generated by Django 2.2.4 on 2019-10-09 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191009_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 9, 0, 43, 10, 946590, tzinfo=utc)),
        ),
    ]
